### ISSUE TITLE
Camera Discussion

### ISSUE THREAD

**Issue by MarioCornell** [Strange-Land/Core#5]
In the original StrangeLand, in server startup screen, the camera is a child of the Canvas; in waiting room, the cameras are all rerun children. 

How should we handle camera when rerun is now an optional components? A persistent researcher camera? Cameras embedded in scenes?

My current idea for the vanilla windows build is:
for researcher, have a persistent camera (don't destroy on load)
for client, the camera is in the player interactableobject prefab

**Comment by DavidGoedicke** [comment]
I just want to share the rational behind the current set up. I am very happy to change it.

The idea was that the windows/Mac build should be able to mimicking what ever camera setup is used on a different system. 

So the startup canvas falls outside of the standard client object interactable object paradigms. Which is why it has its own camera. Not to dissimilar from the IPaddress field interface from the VR screen. So that once done we can load what ever client camera we have. 


So my suggestion given this idea is that we keep the child camera for the startup canvas but make the server spawn a researcher interface and "take over" at is where the camera setup from ReRun and make the 4-camera setup of "native SttangeLand".


Thoughts?

**Comment by MarioCornell** [comment]
All makes sense --- working on it!
